const NOTIFICATION_TYPES = {
  RESULT_PUBLISHED: "RESULT_PUBLISHED",
  RESULT_FAIL: "RESULT_FAIL",

  REAPPEAR_APPROVED: "REAPPEAR_APPROVED",
  REAPPEAR_REJECTED: "REAPPEAR_REJECTED",

  ACHIEVEMENT_APPROVED: "ACHIEVEMENT_APPROVED",
  ACHIEVEMENT_REJECTED: "ACHIEVEMENT_REJECTED",

  // Sent to each faculty a student picks to verify their achievement.
  ACHIEVEMENT_REVIEW_REQUESTED: "ACHIEVEMENT_REVIEW_REQUESTED",
  ACHIEVEMENT_ASSIGNED: "ACHIEVEMENT_ASSIGNED",

  SUBJECT_ASSIGNED: "SUBJECT_ASSIGNED",

  TIMETABLE_APPROVED: "TIMETABLE_APPROVED",
};

module.exports = NOTIFICATION_TYPES;